Elaborated timeout error message
vippsas/vipps-psp-api pull request #130
Opened 2022-10-11 16:23 UTC by alfmags

2022-10-11 16:27 UTC, cloveras commented on vipps-psp-api.md
> +_Only available for whitelisted sale units._
```suggestion
**Please note:** This feature has to be specially enabled by Vipps for eligible sale units: The sale units must be whitelisted by Vipps. Skipping the landing page is typically used at physical points of sale where there is no display available.
```

2022-10-11 16:27 UTC, cloveras requested changes
Looks good! Comments: Nothing substantial.

2022-11-16 09:28 UTC, rebekaburnett commented on vipps-psp-api.md
> +
```suggestion
```

2022-11-16 09:28 UTC, rebekaburnett commented on vipps-psp-api.md
> +
```suggestion
```

2022-11-16 09:30 UTC, rebekaburnett approved these changes
I fixed the conflicts and added the notes

2022-11-16 09:30 UTC, merged