Te 387 psp onboarding api doc update
vippsas/vipps-psp-api pull request #51
Opened 2020-09-08 16:59 UTC by ananthb86

2020-09-08 21:25 UTC, cloveras approved these changes

2020-09-09 05:49 UTC, tht13 approved these changes

2020-09-09 05:50 UTC, tht13 requested changes
Please change the payment.png to a non-branded figma design

2020-09-10 10:12 UTC, tht13 approved these changes

2020-09-10 10:30 UTC, merged